### ISSUE TITLE
sound/vibrate notification + fixed new PM on the main screen

### ISSUE THREAD

**Issue by alebum** [lhchavez/gtalkchat#123]
When a chat is opened and you get a message from another person you're not aware of the new message (the tost comes only for a while) - some sound/vibration options would be useful here.

Also when new message is received from another person and you press the home button there is no notification on the main screen that a new message is waiting

**Comment by limitedmage** [comment]
About your first part, if the app is not open, we cannot control how notifications are delivered, so we cannot change the sound or toast duration. You can look at the Live Tile to see how many toasts there have been since you last opened the app.

Could you explain your second part further? If you open the app and it has unread messages, you will see a toast notifying you of any messages you missed. You will also see how many unread messages you got from each contact over their avatar in both the "online" list and the "recent" list.

**Comment by alebum** [comment]
The first part concerned opened app - there's no sound within gchat and it would be nice if I could hear a sound when a new message arrives.

The second part was about unread messages. You have a conversation with one person, and get the message from another one - message you don't read. When you press the home button and get to the homescreen where gchat is pinned you don't see in the Live Tile that there are unread messages left. Of course when you enter gchat again you will see the notification.

**Comment by limitedmage** [comment]
I've spun these off into two separate issues, #124 and #125.
