### ISSUE TITLE
Gchat does not receive messages from Jabber Transport linked to ICQ account

### ISSUE THREAD

**Issue by limitedmage** [lhchavez/gtalkchat#132]
Original message:

> I do not receive any messages with your free version of gChat. Sending a message works perfectly.
> I'm using a Jabber Transport to connect my ICQ account with my gmail account. Inside of my browser I can chat properly. There I can see those messages I sent from inside the gChat app.

Please investigate.

**Comment by limitedmage** [comment]
Related to #131?

**Comment by lhchavez** [comment]
I think that to receive messages, the user that's sending the message has
to be in the contact list. i'll make a change so that if the user is not in
the contact list, it gets added. if i'm correct about this, expect it to be
fixed in 1.7.
On Jun 14, 2012 12:36 PM, "Juliana Peña" <
reply@reply.github.com>
wrote:

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/20
