### ISSUE TITLE
Contacts sometimes appear repeated

### ISSUE THREAD

**Issue by lhchavez** [lhchavez/gtalkchat#136]

**Comment by hieuman** [comment]
I see this only with one contact, and it happens to be the first person on my contacts list.

**Comment by sovamind** [comment]
I have this same issue. I only have one contact and it seems that I keep getting a duplicate of that contact made each time a new message comes in from the person while the program is in the background on the phone.  I now see the contact three times.

**Comment by MeganByte** [comment]
Exact same problem with me; LG E900

**Comment by MobileRob** [comment]
Same issue ... I have several contacts that show up with their name and then again with their gmail email address (no name, just email address).  This is confusing, since I don't know which one is the one I should be using.  May be caused by people signed into the desktop chat and into their phone's Talk app.

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/3
