### ISSUE TITLE
Support Google two-factor auth

### ISSUE THREAD

**Issue by limitedmage** [lhchavez/gtalkchat#78]
As in http://googleblog.blogspot.com/2011/02/advanced-sign-in-security-for-your.html

**Comment by lhchavez** [comment]
Turns out, Google Talk is not compatible with two-factor auth:

http://www.google.com/support/accounts/bin/static.py?page=guide.cs&guide=1056283&topic=1056286

BUT! Google does support creating an application-speficic password, so you can just activate the feature for your account and create one for Gchat.
